In [1]:
import numpy as np
import pandas as pd
import csv

# By Zeek

In [32]:
path='/home/janati/Desktop/Meryem/IDS-Datasets/Datasets/cic17/Zeek/timeout1/logs/Friday-WorkingHours_conn.log'

df_1 = pd.read_csv(path, sep="\t", comment='#',
                         names=['ts', 'uid', 'id.orig_h', 'id.orig_p',
                                'id.resp_h', 'id.resp_p', 'proto', 'service',
                                'duration',  'orig_bytes', 'resp_bytes',
                                'conn_state', 'local_orig', 'local_resp',
                                'missed_bytes',  'history', 'orig_pkts',
                                'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes',
                                'tunnel_parents'])
df_1 = pd.DataFrame(df_1.values, columns=df_1.columns)
df_1['duration'].replace('-', np.nan, inplace=True)
df_1['duration'] = df_1['duration'].astype(float)

In [33]:
df_1

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents
0,1499428835.357533,CQ1QAF2Q364AqBHG6h,192.168.10.9,1031,192.168.10.3,88,tcp,krb_tcp,0.000707,233,...,RSTR,T,T,0,ShADTdtFar,8,810,8,758,-
1,1499428835.37463,CM4Ivw49ESMXhbOoqj,192.168.10.9,1032,192.168.10.3,88,tcp,krb_tcp,0.000961,313,...,RSTR,T,T,0,ShADTdtFar,10,1050,8,3408,-
2,1499428835.416115,C7Wsem4gb0zTEd9MT1,192.168.10.9,1033,192.168.10.3,88,tcp,krb_tcp,0.001095,1552,...,RSTR,T,T,0,ShADaTdtFr,10,3528,10,3460,-
3,1499428835.417351,CcTLij2dgw1zwJY5y9,192.168.10.9,1034,192.168.10.3,88,tcp,krb_tcp,0.000733,1397,...,RSTR,T,T,0,ShADTdtFar,8,3138,8,3164,-
4,1499428835.493599,CPxtnL1kfOlvfEVnQ3,192.168.10.9,1036,192.168.10.3,88,tcp,krb_tcp,0.000907,1565,...,RSTR,T,T,0,ShADTadtFr,10,3554,10,3472,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
548575,1499457543.827709,CGFtjWTDbGmhb7C36,192.168.10.14,59111,23.10.108.151,443,tcp,ssl,217.124589,31696,...,SF,T,F,0,ShADadTTfF,48,33645,53,11036,-
548576,1499457543.027241,CtKoJH1eaqxht0KMme,192.168.10.14,59099,157.240.18.5,443,tcp,ssl,182.615533,32414,...,SF,T,F,0,ShADadFfRr,65,35026,61,10702,-
548577,1499457542.416454,CQRGxjc3uAmzlS1nh,192.168.10.14,59079,172.217.10.66,443,tcp,ssl,181.621866,23715,...,S1,T,F,0,ShADad,27,24807,45,7472,-
548578,1499457474.404687,CScfMM3D44ZpFpNsVi,192.168.10.17,54911,87.250.250.210,443,tcp,ssl,275.592901,1442,...,S1,T,F,0,ShADad,22,2342,31,8148,-
548579,1499457353.782535,CPAsZ1p85iOJEPMhi,192.168.10.19,35670,54.171.7.143,443,tcp,ssl,399.973390,24304,...,S1,T,F,1050,ShADadg,88,28888,58,38666,-

In [35]:
df_1["duration"].max(), df_1["duration"].min()

(1658.651615, 1e-06)

In [36]:
path='/home/janati/Desktop/Meryem/IDS-Datasets/Datasets/cic17/Zeek/timeout60/logs/Friday-WorkingHours_conn.log'

df_60 = pd.read_csv(path, sep="\t", comment='#',
                         names=['ts', 'uid', 'id.orig_h', 'id.orig_p',
                                'id.resp_h', 'id.resp_p', 'proto', 'service',
                                'duration',  'orig_bytes', 'resp_bytes',
                                'conn_state', 'local_orig', 'local_resp',
                                'missed_bytes',  'history', 'orig_pkts',
                                'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes',
                                'tunnel_parents'])
df_60 = pd.DataFrame(df_60.values, columns=df_60.columns)
df_60['duration'].replace('-', np.nan, inplace=True)
df_60['duration'] = df_60['duration'].astype(float)

In [37]:
df_60

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents
0,1499428835.357533,C29z4PTq3CLhQE1o8,192.168.10.9,1031,192.168.10.3,88,tcp,krb_tcp,0.000707,233,...,RSTR,T,T,0,ShADTdtFar,8,810,8,758,-
1,1499428835.37463,C85vRv35yl2qb5543b,192.168.10.9,1032,192.168.10.3,88,tcp,krb_tcp,0.000961,313,...,RSTR,T,T,0,ShADTdtFar,10,1050,8,3408,-
2,1499428835.416115,C8QLlT3cSYa6Oss454,192.168.10.9,1033,192.168.10.3,88,tcp,krb_tcp,0.001095,1552,...,RSTR,T,T,0,ShADaTdtFr,10,3528,10,3460,-
3,1499428835.417351,Clay7J3gvz3QRMshTd,192.168.10.9,1034,192.168.10.3,88,tcp,krb_tcp,0.000733,1397,...,RSTR,T,T,0,ShADTdtFar,8,3138,8,3164,-
4,1499428835.493599,CCYNn12RDtqE7IDPMk,192.168.10.9,1036,192.168.10.3,88,tcp,krb_tcp,0.000907,1565,...,RSTR,T,T,0,ShADTadtFr,10,3554,10,3472,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540741,1499428915.150815,CrWx6X6UQM7H4vopb,192.168.10.17,123,108.59.2.24,123,udp,ntp,27973.036995,5040,...,SF,T,F,0,Dd,105,7980,105,7980,-
540742,1499428910.150839,Cw7vPF2eISUGVUVaHj,192.168.10.17,123,52.60.76.61,123,udp,ntp,28030.038431,5136,...,SF,T,F,0,Dd,107,8132,107,8132,-
540743,1499428900.135618,C30DmV0uGiB2uArTk,192.168.10.17,123,192.168.10.3,123,udp,ntp,28665.024070,10176,...,SF,T,T,0,Dd,212,16112,212,16112,-
540744,1499454301.10134,Cj4KaD1IgPNgqBhHzl,192.168.10.9,50396,192.168.10.3,389,udp,-,0.000177,414,...,SF,T,T,0,Dd,2,470,2,382,-
540745,1499428911.150824,CZTsl42iQcUBP5MkI7,192.168.10.17,123,144.217.163.175,123,udp,ntp,28064.024857,5088,...,SF,T,F,0,Dd,106,8056,105,7980,-

In [39]:
df_60["duration"].max(), df_60["duration"].min()

(28912.951521, 1e-06)

In [21]:
path='/home/janati/Desktop/Meryem/IDS-Datasets/Preprocessing/preprocessByZeek/ustc/Benign/logs/conn_15.log'

df3 = pd.read_csv(path, sep="\t", comment='#',
                         names=['ts', 'uid', 'id.orig_h', 'id.orig_p',
                                'id.resp_h', 'id.resp_p', 'proto', 'service',
                                'duration',  'orig_bytes', 'resp_bytes',
                                'conn_state', 'local_orig', 'local_resp',
                                'missed_bytes',  'history', 'orig_pkts',
                                'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes',
                                'tunnel_parents'])
df3 = pd.DataFrame(df3.values, columns=df3.columns)

In [22]:
df3

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents
0,183137.394613,CW2Jj14JkCI8WIyFCc,1.1.172.104,17515,1.2.63.173,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
1,183137.394601,C5ZjCv3f05eXntIHL8,1.1.171.218,18327,1.2.246.220,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
2,183137.394599,ChAizn25xjrhKZ5e2g,1.1.83.102,53295,1.2.195.119,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
3,183137.394597,Cgoo453chndaXrAGuf,1.1.95.134,49359,1.2.8.13,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
4,183137.394591,Cil1Yy4SF02TLSJEeh,1.1.245.131,27910,1.2.104.64,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7519,183137.386512,CSrDlW3VKK13EqOBGa,1.1.228.0,2015,1.2.183.37,443,tcp,-,0.000144,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7520,183137.387072,Clo2qw3YvK2CUZEMGl,1.1.247.40,28390,1.2.222.36,443,tcp,-,0.000130,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7521,183137.373431,CuC2dp3sC5XpE8qL29,1.1.186.13,35381,1.2.133.124,443,tcp,-,0.000149,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7522,183137.387092,CSFkDd3wsBdGI1VkWd,1.1.38.67,20574,1.2.255.147,443,tcp,-,0.000057,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7523,183137.387095,CZguqg3ONiV8p4bTMi,1.1.13.169,35571,1.2.134.55,443,tcp,-,0.000101,0,...,OTH,F,F,0,^dA,1,52,1,1457,-

In [23]:
path='/home/janati/Desktop/Meryem/IDS-Datasets/Preprocessing/preprocessByZeek/ustc/Benign/logs/conn_15_2.log'

df3 = pd.read_csv(path, sep="\t", comment='#',
                         names=['ts', 'uid', 'id.orig_h', 'id.orig_p',
                                'id.resp_h', 'id.resp_p', 'proto', 'service',
                                'duration',  'orig_bytes', 'resp_bytes',
                                'conn_state', 'local_orig', 'local_resp',
                                'missed_bytes',  'history', 'orig_pkts',
                                'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes',
                                'tunnel_parents'])
df3 = pd.DataFrame(df3.values, columns=df3.columns)

In [24]:
df3

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents
0,183137.394613,Ce5Uv2MgnxH2CUlg,1.1.172.104,17515,1.2.63.173,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
1,183137.394601,C95MqP1wUzZWQqOby4,1.1.171.218,18327,1.2.246.220,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
2,183137.3946,C7o7KLMlh3bTwyfSk,1.1.109.144,45112,1.2.23.126,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
3,183137.394589,CRJdXp3IFyOp339NV6,1.1.145.214,64741,1.2.248.38,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
4,183137.394578,CVvjNx2BFpCLwmYM3d,1.1.22.128,15731,1.2.140.181,443,tcp,-,0.000037,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7519,183137.383107,CWzqtT3YGbSqs9nbe5,1.1.50.166,60484,1.2.239.133,443,tcp,-,0.000195,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7520,183137.387083,CP8AkBWjvXo01xGBa,1.1.3.209,41669,1.2.157.255,443,tcp,-,0.000050,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7521,183137.387088,Cv78R911UFR3YJxWJ7,1.1.255.249,30948,1.2.116.43,443,tcp,-,0.000026,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7522,183137.387621,C2FTjP1gYq45ZuubW4,1.1.91.108,53068,1.2.202.143,443,tcp,-,0.000093,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7523,183137.387095,CfpgZu2h3r8QssNZ44,1.1.13.169,35571,1.2.134.55,443,tcp,-,0.000101,0,...,OTH,F,F,0,^dA,1,52,1,1457,-

In [119]:
path='/home/janati/Desktop/Meryem/IDS-Datasets/Preprocessing/preprocessByZeek/cic17/conn_60.log'

df3 = pd.read_csv(path, sep="\t", comment='#',
                         names=['ts', 'uid', 'id.orig_h', 'id.orig_p',
                                'id.resp_h', 'id.resp_p', 'proto', 'service',
                                'duration',  'orig_bytes', 'resp_bytes',
                                'conn_state', 'local_orig', 'local_resp',
                                'missed_bytes',  'history', 'orig_pkts',
                                'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes',
                                'tunnel_parents'])
df3 = pd.DataFrame(df3.values, columns=df3.columns)

In [116]:
df3 #1

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents
0,1499428835.357533,CZbLEE9vFnM8d4VL4,192.168.10.9,1031,192.168.10.3,88,tcp,krb_tcp,0.000707,233,...,RSTR,T,T,0,ShADTdtFar,8,810,8,758,-
1,1499428835.37463,CMHFWE10udCUu7N0O7,192.168.10.9,1032,192.168.10.3,88,tcp,krb_tcp,0.000961,313,...,RSTR,T,T,1532,ShADTcgFar,10,1050,6,264,-
2,1499428835.416115,CRlAdv3mbgbWsvyfze,192.168.10.9,1033,192.168.10.3,88,tcp,-,0.001095,1552,...,RSTR,T,T,3070,ShACaGcgFr,8,344,8,344,-
3,1499428835.417351,CM7wa6pPks29AJGn8,192.168.10.9,1034,192.168.10.3,88,tcp,krb_tcp,0.000733,1397,...,RSTR,T,T,0,ShADTdtFar,8,3138,8,3164,-
4,1499428835.493599,CgDcR43FIbHQx0xT85,192.168.10.9,1036,192.168.10.3,88,tcp,-,0.000907,1565,...,RSTR,T,T,3089,ShACaGcgFr,8,344,8,344,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
548580,1499457543.027241,CGXZnn111n0htIbSkj,192.168.10.14,59099,157.240.18.5,443,tcp,ssl,182.615533,32414,...,SF,T,F,23810,ShADadCGFfRr,59,10976,61,10702,-
548581,1499457544.809613,CfyOo9Ckps9fpFDKk,192.168.10.14,59129,74.121.142.165,443,tcp,ssl,210.830927,1587,...,S1,T,F,0,ShADadTT,28,2740,27,4786,-
548582,1499457542.416454,CKCSY64T9Dq3uxZZnj,192.168.10.14,59079,172.217.10.66,443,tcp,ssl,181.621866,23715,...,S1,T,F,22894,ShADadCGG,22,1713,45,7472,-
548583,1499457474.404687,Cs1dV82MVRiKwGPoq7,192.168.10.17,54911,87.250.250.210,443,tcp,ssl,275.592901,1442,...,S1,T,F,3219,ShADadcg,22,2342,30,4889,-
548584,1499457353.782535,CIypR33BZgch4Trill,192.168.10.19,35670,54.171.7.143,443,tcp,ssl,399.973390,24304,...,S1,T,F,1050,ShADadg,88,28888,58,38666,-

# By Argus

In [14]:
path='/home/janati/Desktop/Meryem/IDS-Datasets/Datasets/cic17/Argus/timeout1/features/Friday-WorkingHours_features.csv'
column_names = ['srcid', 'rank', 'stime', 'ltime', 'trans', 'flgs', 'seq', 'dur', 'runtime', 'idle', 'mean',
                'stddev', 'sum', 'min', 'max', 'smac', 'dmac', 'soui', 'doui', 'saddr', 'daddr', 'proto',
                'sport', 'dport', 'stos', 'dtos', 'sdsb', 'ddsb', 'sco', 'dco', 'sttl', 'dttl', 'shops',
                'dhops', 'sipid', 'dipid', 'smpls', 'dmpls', 'autoid', 'sas', 'das', 'ias', 'cause', 'nstroke',
                'snstroke', 'dnstroke', 'pkts', 'spkts', 'dpkts', 'bytes', 'sbytes', 'dbytes', 'appbytes',
                'sappbytes', 'dappbytes', 'pcr', 'load', 'sload', 'dload', 'loss', 'sloss', 'dloss', 'ploss',
                'psloss', 'pdloss', 'retrans', 'sretrans', 'dretrans', 'pretrans', 'psretrans', 'pdretrans',
                'sgap', 'dgap', 'rate', 'srate', 'drate', 'dir', 'sintpkt', 'sintdist', 'sintpktact',
                'sintdistact', 'sintpktidl', 'sintdistidl', 'dintpkt', 'dintdist', 'dintpktact', 
                'dintdistact', 'dintpktidl', 'dintdistidl', 'sjit', 'sjitact', 'sjitidle', 'djit',
                'djitact', 'djitidle', 'state', 'label', 'suser', 'duser', 'swin', 'dwin', 'svlan', 'dvlan',
                'svid', 'dvid', 'svpri', 'dvpri', 'srng', 'erng', 'stcpb', 'dtcpb', 'tcprtt', 'synack',
                'ackdat', 'tcpopt']

# df1 = pd.read_csv(path, sep="\t", header=0)
df1 = pd.read_csv(path)
# df1 = pd.DataFrame(df1.values, columns=df1.columns)

In [15]:
df1

,SrcId,Rank,StartTime,LastTime,Trans,Flgs,Seq,Dur,RunTime,IdleTime,...,sVpri,dVpri,SRange,ERange,SrcTCPBase,DstTCPBase,TcpRtt,SynAck,AckDat,TcpOpt
0,0.0.0.0,NaN,02:58:29.365540,02:58:29.364766,NaN,,0,0.000774,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN
1,0.0.0.0,1.0,12:59:39.599128,12:59:39.599128,1.0,*,1,0.000000,0.000000,1.722910e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN
2,0.0.0.0,2.0,12:59:43.018330,12:59:43.018330,1.0,*,2,0.000000,0.000000,1.722910e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN
3,0.0.0.0,3.0,12:59:45.798480,12:59:45.798480,1.0,*,3,0.000000,0.000000,1.722910e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN
4,0.0.0.0,4.0,12:59:46.231251,12:59:46.231251,1.0,*,4,0.000000,0.000000,1.722910e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
947703,0.0.0.0,947703.0,21:02:40.543598,21:02:40.565487,1.0,e,897701,0.021889,0.021889,1.722910e+09,...,NaN,NaN,NaN,NaN,1.366821e+08,2.893493e+09,0.000000,0.000000,0.000000,S
947704,0.0.0.0,947704.0,21:02:40.720915,21:02:40.759135,1.0,e,897702,0.038220,0.038220,1.722910e+09,...,NaN,NaN,NaN,NaN,1.129755e+09,4.192530e+09,0.000000,0.000000,0.000000,T
947705,0.0.0.0,947705.0,21:02:40.952185,21:02:41.005391,1.0,e,897686,0.053206,0.053206,1.722910e+09,...,NaN,NaN,NaN,NaN,4.232390e+09,1.094031e+09,0.000000,0.000000,0.000000,S
947706,0.0.0.0,947706.0,21:02:40.977798,21:02:41.169108,1.0,e,897703,0.191310,0.191310,1.722910e+09,...,NaN,NaN,NaN,NaN,1.682897e+09,2.636445e+09,0.095413,0.095366,0.000047,Mws T
947707,0.0.0.0,947706.0,02:58:44.369029,02:58:29.364766,NaN,,0,15.004263,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN

In [16]:
df1["Dur"].min(), df1["Dur"].max(), df1.shape

(0.0, 15.004263, (947708, 109))

In [17]:
path='/home/janati/Desktop/Meryem/IDS-Datasets/Datasets/cic17/Argus/timeout60/features/Friday-WorkingHours_features.csv'

# df1 = pd.read_csv(path, sep="\t", header=0)
df2 = pd.read_csv(path)
# df1 = pd.DataFrame(df1.values, columns=df1.columns)

In [18]:
df2.head()

,SrcId,Rank,StartTime,LastTime,Trans,Flgs,Seq,Dur,RunTime,IdleTime,...,sVpri,dVpri,SRange,ERange,SrcTCPBase,DstTCPBase,TcpRtt,SynAck,AckDat,TcpOpt
0,0.0.0.0,NaN,02:53:19.278086,02:53:19.277298,NaN,,0,0.000788,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN
1,0.0.0.0,1.0,12:59:39.599128,12:59:39.599128,1.0,*,1,0.000000,0.0,1.722909e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN
2,0.0.0.0,2.0,12:59:43.018330,12:59:43.018330,1.0,*,2,0.000000,0.0,1.722909e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN
3,0.0.0.0,3.0,12:59:45.798480,12:59:45.798480,1.0,*,3,0.000000,0.0,1.722909e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN
4,0.0.0.0,4.0,12:59:46.231251,12:59:46.231251,1.0,*,4,0.000000,0.0,1.722909e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN

In [27]:
df2["Dur"].min(), df2["Dur"].max() , df2.shape

(0.0, 15.004567, (947783, 109))

In [29]:
path='/home/janati/Desktop/Meryem/IDS-Datasets/Datasets/cic17/Argus/timeout2/features/Friday-WorkingHours_features.csv'

# df1 = pd.read_csv(path, sep="\t", header=0)
df3 = pd.read_csv(path)
# df1 = pd.DataFrame(df1.values, columns=df1.columns)

In [30]:
df3["Dur"].min(), df3["Dur"].max() , df3.shape

(0.0, 15.004384, (947708, 109))