In [15]:
import numpy as np
import pandas as pd
import csv

In [16]:
path='/home/janati/Desktop/Meryem/IDS-Datasets/Datasets/ustc/Zeek/timeout1/Benign/conn_logs/Outlook_conn.log'

df_1 = pd.read_csv(path, sep="\t", comment='#',
                         names=['ts', 'uid', 'id.orig_h', 'id.orig_p',
                                'id.resp_h', 'id.resp_p', 'proto', 'service',
                                'duration',  'orig_bytes', 'resp_bytes',
                                'conn_state', 'local_orig', 'local_resp',
                                'missed_bytes',  'history', 'orig_pkts',
                                'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes',
                                'tunnel_parents'])
df_1 = pd.DataFrame(df_1.values, columns=df_1.columns)
df_1['duration'].replace('-', np.nan, inplace=True)
df_1['duration'] = df_1['duration'].astype(float)

In [17]:
df_1

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents
0,183137.3946,CiXJnPfZ4nkjZo5jd,1.1.109.144,45112,1.2.23.126,443,tcp,-,NaN,-,...,OTH,F,F,0,^d,0,0,1,1457,-
1,183137.394599,CEPlPz1lr2cbAOgxR9,1.1.83.102,53295,1.2.195.119,443,tcp,-,NaN,-,...,OTH,F,F,0,^d,0,0,1,1457,-
2,183137.394595,Cf73L8zN0SbbUTOAa,1.1.49.127,61858,1.2.236.223,443,tcp,-,NaN,-,...,OTH,F,F,0,^d,0,0,1,1457,-
3,183137.394594,Coz0cr3slU1phmZkmb,1.1.139.69,54313,1.2.215.105,443,tcp,-,NaN,-,...,OTH,F,F,0,^d,0,0,1,1457,-
4,183137.394589,CWrEZMtyMkIWXjeZg,1.1.145.214,64741,1.2.248.38,443,tcp,-,NaN,-,...,OTH,F,F,0,^d,0,0,1,1457,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7519,183137.387068,CB6Qm729YnTmEx8WIb,1.1.170.21,62674,1.2.240.18,443,tcp,-,0.000055,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7520,183137.387083,CPasOC11Aj9MEWbKba,1.1.3.209,41669,1.2.157.255,443,tcp,-,0.000050,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7521,183137.387084,CAUeXd333exKzgCj3b,1.1.103.11,48151,1.2.11.92,443,tcp,-,0.000076,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7522,183137.389405,C4ptgw1bX1dZFhS8Pc,1.1.204.82,8898,1.2.170.5,443,tcp,-,0.000031,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7523,183137.387088,Cg2lOE13b8BsLqoge6,1.1.255.249,30948,1.2.116.43,443,tcp,-,0.000026,0,...,OTH,F,F,0,^dA,1,52,1,1457,-

In [18]:
df_1["duration"].max(), df_1["duration"].min()

(0.000354, 1.9e-05)

In [26]:
path='/home/janati/Desktop/Meryem/IDS-Datasets/Datasets/ustc/Zeek/timeout60/Benign/conn_logs/Outlook_conn.log'

df_60 = pd.read_csv(path, sep="\t", comment='#',
                         names=['ts', 'uid', 'id.orig_h', 'id.orig_p',
                                'id.resp_h', 'id.resp_p', 'proto', 'service',
                                'duration',  'orig_bytes', 'resp_bytes',
                                'conn_state', 'local_orig', 'local_resp',
                                'missed_bytes',  'history', 'orig_pkts',
                                'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes',
                                'tunnel_parents'])
df_60 = pd.DataFrame(df_60.values, columns=df_60.columns)
df_60['duration'].replace('-', np.nan, inplace=True)
df_60['duration'] = df_60['duration'].astype(float)

In [27]:
df_60

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents
0,183137.394602,CTvJu74Ddcyd8BxDmj,1.1.153.18,21948,1.2.80.253,443,tcp,-,NaN,-,...,OTH,F,F,0,^d,0,0,1,1457,-
1,183137.394601,CiSLs42uC1uBcsdkej,1.1.171.218,18327,1.2.246.220,443,tcp,-,NaN,-,...,OTH,F,F,0,^d,0,0,1,1457,-
2,183137.394595,CWL3qTXvB8YdV2r1g,1.1.49.127,61858,1.2.236.223,443,tcp,-,NaN,-,...,OTH,F,F,0,^d,0,0,1,1457,-
3,183137.394594,CSMFWB2rZygylMVFx3,1.1.139.69,54313,1.2.215.105,443,tcp,-,NaN,-,...,OTH,F,F,0,^d,0,0,1,1457,-
4,183137.394592,CxVEC62onRC9nwNtKi,1.1.23.128,16026,1.2.57.223,443,tcp,-,NaN,-,...,OTH,F,F,0,^d,0,0,1,1457,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7519,183137.387063,CtHdXD1TX6t3y6xR01,1.1.92.87,47509,1.2.0.216,443,tcp,-,0.000131,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7520,183137.379494,CHpFPuUEt5riSDehj,1.1.220.127,43236,1.2.164.31,443,tcp,-,0.000057,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7521,183137.387064,C2BCZ91g1sSjiAhXli,1.1.72.202,51957,1.2.114.54,443,tcp,-,0.000049,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7522,183137.387068,CcntVM35aAqyMbhDvj,1.1.170.21,62674,1.2.240.18,443,tcp,-,0.000055,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7523,183137.387083,CwBzhs3Qxd98eahdBf,1.1.3.209,41669,1.2.157.255,443,tcp,-,0.000050,0,...,OTH,F,F,0,^dA,1,52,1,1457,-

In [28]:
df_60["duration"].max(), df_60["duration"].min()

(0.000354, 1.9e-05)

In [21]:
path='/home/janati/Desktop/Meryem/IDS-Datasets/Preprocessing/preprocessByZeek/ustc/Benign/logs/conn_15.log'

df3 = pd.read_csv(path, sep="\t", comment='#',
                         names=['ts', 'uid', 'id.orig_h', 'id.orig_p',
                                'id.resp_h', 'id.resp_p', 'proto', 'service',
                                'duration',  'orig_bytes', 'resp_bytes',
                                'conn_state', 'local_orig', 'local_resp',
                                'missed_bytes',  'history', 'orig_pkts',
                                'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes',
                                'tunnel_parents'])
df3 = pd.DataFrame(df3.values, columns=df3.columns)

In [22]:
df3

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents
0,183137.394613,CW2Jj14JkCI8WIyFCc,1.1.172.104,17515,1.2.63.173,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
1,183137.394601,C5ZjCv3f05eXntIHL8,1.1.171.218,18327,1.2.246.220,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
2,183137.394599,ChAizn25xjrhKZ5e2g,1.1.83.102,53295,1.2.195.119,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
3,183137.394597,Cgoo453chndaXrAGuf,1.1.95.134,49359,1.2.8.13,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
4,183137.394591,Cil1Yy4SF02TLSJEeh,1.1.245.131,27910,1.2.104.64,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7519,183137.386512,CSrDlW3VKK13EqOBGa,1.1.228.0,2015,1.2.183.37,443,tcp,-,0.000144,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7520,183137.387072,Clo2qw3YvK2CUZEMGl,1.1.247.40,28390,1.2.222.36,443,tcp,-,0.000130,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7521,183137.373431,CuC2dp3sC5XpE8qL29,1.1.186.13,35381,1.2.133.124,443,tcp,-,0.000149,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7522,183137.387092,CSFkDd3wsBdGI1VkWd,1.1.38.67,20574,1.2.255.147,443,tcp,-,0.000057,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7523,183137.387095,CZguqg3ONiV8p4bTMi,1.1.13.169,35571,1.2.134.55,443,tcp,-,0.000101,0,...,OTH,F,F,0,^dA,1,52,1,1457,-

In [23]:
path='/home/janati/Desktop/Meryem/IDS-Datasets/Preprocessing/preprocessByZeek/ustc/Benign/logs/conn_15_2.log'

df3 = pd.read_csv(path, sep="\t", comment='#',
                         names=['ts', 'uid', 'id.orig_h', 'id.orig_p',
                                'id.resp_h', 'id.resp_p', 'proto', 'service',
                                'duration',  'orig_bytes', 'resp_bytes',
                                'conn_state', 'local_orig', 'local_resp',
                                'missed_bytes',  'history', 'orig_pkts',
                                'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes',
                                'tunnel_parents'])
df3 = pd.DataFrame(df3.values, columns=df3.columns)

In [24]:
df3

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents
0,183137.394613,Ce5Uv2MgnxH2CUlg,1.1.172.104,17515,1.2.63.173,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
1,183137.394601,C95MqP1wUzZWQqOby4,1.1.171.218,18327,1.2.246.220,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
2,183137.3946,C7o7KLMlh3bTwyfSk,1.1.109.144,45112,1.2.23.126,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
3,183137.394589,CRJdXp3IFyOp339NV6,1.1.145.214,64741,1.2.248.38,443,tcp,-,-,-,...,OTH,F,F,0,^d,0,0,1,1457,-
4,183137.394578,CVvjNx2BFpCLwmYM3d,1.1.22.128,15731,1.2.140.181,443,tcp,-,0.000037,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7519,183137.383107,CWzqtT3YGbSqs9nbe5,1.1.50.166,60484,1.2.239.133,443,tcp,-,0.000195,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7520,183137.387083,CP8AkBWjvXo01xGBa,1.1.3.209,41669,1.2.157.255,443,tcp,-,0.000050,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7521,183137.387088,Cv78R911UFR3YJxWJ7,1.1.255.249,30948,1.2.116.43,443,tcp,-,0.000026,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7522,183137.387621,C2FTjP1gYq45ZuubW4,1.1.91.108,53068,1.2.202.143,443,tcp,-,0.000093,0,...,OTH,F,F,0,^dA,1,52,1,1457,-
7523,183137.387095,CfpgZu2h3r8QssNZ44,1.1.13.169,35571,1.2.134.55,443,tcp,-,0.000101,0,...,OTH,F,F,0,^dA,1,52,1,1457,-

In [119]:
path='/home/janati/Desktop/Meryem/IDS-Datasets/Preprocessing/preprocessByZeek/cic17/conn_60.log'

df3 = pd.read_csv(path, sep="\t", comment='#',
                         names=['ts', 'uid', 'id.orig_h', 'id.orig_p',
                                'id.resp_h', 'id.resp_p', 'proto', 'service',
                                'duration',  'orig_bytes', 'resp_bytes',
                                'conn_state', 'local_orig', 'local_resp',
                                'missed_bytes',  'history', 'orig_pkts',
                                'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes',
                                'tunnel_parents'])
df3 = pd.DataFrame(df3.values, columns=df3.columns)

In [116]:
df3 #1

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents
0,1499428835.357533,CZbLEE9vFnM8d4VL4,192.168.10.9,1031,192.168.10.3,88,tcp,krb_tcp,0.000707,233,...,RSTR,T,T,0,ShADTdtFar,8,810,8,758,-
1,1499428835.37463,CMHFWE10udCUu7N0O7,192.168.10.9,1032,192.168.10.3,88,tcp,krb_tcp,0.000961,313,...,RSTR,T,T,1532,ShADTcgFar,10,1050,6,264,-
2,1499428835.416115,CRlAdv3mbgbWsvyfze,192.168.10.9,1033,192.168.10.3,88,tcp,-,0.001095,1552,...,RSTR,T,T,3070,ShACaGcgFr,8,344,8,344,-
3,1499428835.417351,CM7wa6pPks29AJGn8,192.168.10.9,1034,192.168.10.3,88,tcp,krb_tcp,0.000733,1397,...,RSTR,T,T,0,ShADTdtFar,8,3138,8,3164,-
4,1499428835.493599,CgDcR43FIbHQx0xT85,192.168.10.9,1036,192.168.10.3,88,tcp,-,0.000907,1565,...,RSTR,T,T,3089,ShACaGcgFr,8,344,8,344,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
548580,1499457543.027241,CGXZnn111n0htIbSkj,192.168.10.14,59099,157.240.18.5,443,tcp,ssl,182.615533,32414,...,SF,T,F,23810,ShADadCGFfRr,59,10976,61,10702,-
548581,1499457544.809613,CfyOo9Ckps9fpFDKk,192.168.10.14,59129,74.121.142.165,443,tcp,ssl,210.830927,1587,...,S1,T,F,0,ShADadTT,28,2740,27,4786,-
548582,1499457542.416454,CKCSY64T9Dq3uxZZnj,192.168.10.14,59079,172.217.10.66,443,tcp,ssl,181.621866,23715,...,S1,T,F,22894,ShADadCGG,22,1713,45,7472,-
548583,1499457474.404687,Cs1dV82MVRiKwGPoq7,192.168.10.17,54911,87.250.250.210,443,tcp,ssl,275.592901,1442,...,S1,T,F,3219,ShADadcg,22,2342,30,4889,-
548584,1499457353.782535,CIypR33BZgch4Trill,192.168.10.19,35670,54.171.7.143,443,tcp,ssl,399.973390,24304,...,S1,T,F,1050,ShADadg,88,28888,58,38666,-

In [118]:
df3 #5

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents
0,1499428835.357533,CgS9PY3bSvj0XRl9Ad,192.168.10.9,1031,192.168.10.3,88,tcp,krb_tcp,0.000707,233,...,RSTR,T,T,0,ShADTdtFar,8,810,8,758,-
1,1499428835.37463,C99Vle4jGXLB8VyQYd,192.168.10.9,1032,192.168.10.3,88,tcp,krb_tcp,0.000961,313,...,RSTR,T,T,1532,ShADTcgFar,10,1050,6,264,-
2,1499428835.416115,CniQhd3C3Lhy5A6Vfh,192.168.10.9,1033,192.168.10.3,88,tcp,-,0.001095,1552,...,RSTR,T,T,3070,ShACaGcgFr,8,344,8,344,-
3,1499428835.417351,CYe8f83PaQEOuf3877,192.168.10.9,1034,192.168.10.3,88,tcp,krb_tcp,0.000733,1397,...,RSTR,T,T,0,ShADTdtFar,8,3138,8,3164,-
4,1499428835.493599,CAAeog1h1X5FRPfMZ3,192.168.10.9,1036,192.168.10.3,88,tcp,-,0.000907,1565,...,RSTR,T,T,3089,ShACaGcgFr,8,344,8,344,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542929,1499454998.54837,C9Zfk5rpuZagIg6gj,172.16.0.1,3,192.168.10.5,1,icmp,-,2654.178071,2408,...,OTH,T,T,0,-,48,3752,0,0,-
542930,1499454995.548369,CyJ7Of24VoAPh4yHEi,172.16.0.1,3,192.168.10.9,1,icmp,-,2673.108096,3448,...,OTH,T,T,0,-,68,5352,0,0,-
542931,1499454987.3783,CCykPz2HWpqigCfAAh,172.16.0.1,3,192.168.10.8,1,icmp,-,2697.228362,6632,...,OTH,T,T,0,-,131,10300,0,0,-
542932,1499454987.378294,CGNoCm4FCjXGZbjTRb,172.16.0.1,3,192.168.10.15,1,icmp,-,2697.228369,6840,...,OTH,T,T,0,-,135,10620,0,0,-
542933,1499428842.430758,CSohHg31O2LENUTw8,192.168.10.25,123,17.253.14.125,123,udp,ntp,28912.951521,21744,...,SF,T,F,0,Dd,453,34428,453,34428,-

In [120]:
df3 #60

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents
0,1499428835.357533,CnL3TxNiOJedKWTkh,192.168.10.9,1031,192.168.10.3,88,tcp,krb_tcp,0.000707,233,...,RSTR,T,T,0,ShADTdtFar,8,810,8,758,-
1,1499428835.37463,CxLo5OuARQ256t7U3,192.168.10.9,1032,192.168.10.3,88,tcp,krb_tcp,0.000961,313,...,RSTR,T,T,1532,ShADTcgFar,10,1050,6,264,-
2,1499428835.416115,CD9jswa2XG4QJb2Jc,192.168.10.9,1033,192.168.10.3,88,tcp,-,0.001095,1552,...,RSTR,T,T,3070,ShACaGcgFr,8,344,8,344,-
3,1499428835.417351,CSlGK126Izmwek7Z45,192.168.10.9,1034,192.168.10.3,88,tcp,krb_tcp,0.000733,1397,...,RSTR,T,T,0,ShADTdtFar,8,3138,8,3164,-
4,1499428835.493599,Cy5boZ2l1jOj8AXSUh,192.168.10.9,1036,192.168.10.3,88,tcp,-,0.000907,1565,...,RSTR,T,T,3089,ShACaGcgFr,8,344,8,344,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540744,1499429257.841682,CURfYn4HHqbb1zvwU1,192.168.10.12,123,192.168.10.3,123,udp,ntp,27641.957797,7488,...,SF,T,T,0,Dd,156,11856,156,11856,-
540745,1499429544.519605,CAEegs44fjNpxPcQe,192.168.10.19,123,198.60.22.240,123,udp,ntp,28129.067749,4992,...,SF,T,F,0,Dd,104,7904,104,7904,-
540746,1499429530.39779,COXroh38iW53ygGCH4,192.168.10.19,138,192.168.10.255,138,udp,-,27883.500642,137475,...,S0,T,T,0,D,585,153855,0,0,-
540747,1499428915.150815,CYSeMZDgQWZV3QG4,192.168.10.17,123,108.59.2.24,123,udp,ntp,27973.036995,5040,...,SF,T,F,0,Dd,105,7980,105,7980,-
540748,1499428841.949002,CcRogN1idqmJ2d3RB4,192.168.10.50,138,192.168.10.255,138,udp,-,28280.017601,256168,...,S0,T,T,0,D,1136,287976,0,0,-

In [91]:
df3["duration"].max(), df3["duration"].min()

(28912.951521, 1e-06)

In [86]:
df3["duration"].min()

1e-06

In [89]:
df3['duration'].replace('-', np.nan, inplace=True)

In [90]:
df3['duration'] = df3['duration'].astype(float)

In [46]:
df3["conn_state"].unique()

array(['S0', 'OTH', 'SHR', 'SF', 'S1', 'SH'], dtype=object)

In [39]:
df3.columns

Index(['ts', 'uid', 'id.orig_h', 'id.orig_p', 'id.resp_h', 'id.resp_p',
       'proto', 'service', 'duration', 'orig_bytes', 'resp_bytes',
       'conn_state', 'local_orig', 'local_resp', 'missed_bytes', 'history',
       'orig_pkts', 'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes',
       'tunnel_parents'],
      dtype='object')

In [71]:
pwd

'/home/janati/Desktop/Meryem/IDS-Datasets/Preprocessing/preprocessByZeek/ustc'

In [113]:
path='/home/janati/Desktop/Meryem/IDS-Datasets/pcaps/cic17/pcaps/argus/Friday.csv'

df = pd.read_csv(path, names=['duration'])
df = pd.DataFrame(df.values, columns=df.columns)

/tmp/ipykernel_29091/3289186740.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, names=['duration'])

In [111]:
# timeout=1min
df

            duration
0               Dur
1           0.000792
2           0.000000
3           0.000000
4           0.000000
...              ...
2843348     0.021889
2843349      0.03822
2843350     0.053206
2843351      0.19131
2843352    13.004171

[2843353 rows x 1 columns]

In [114]:
# timeout=60min
df

            duration
0               Dur
1           0.000792
2           0.000000
3           0.000000
4           0.000000
...              ...
3791131     0.021889
3791132      0.03822
3791133     0.053206
3791134      0.19131
3791135    13.004202

[3791136 rows x 1 columns]